<a href="https://colab.research.google.com/github/arunprithviraj/PyTorchSelfStudy/blob/main/PytorchSelfStudy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(pd.__version__)
print(np.__version__)


2.5.1+cu124
2.2.2
1.26.4


*[italicized text](https://)*# New Section

In [ ]:
#scalar datatype
scalar = torch.tensor(7)
print(f"Scalar:{scalar}")
scalar.ndim
scalar.shape

Scalar:7


torch.Size([])

In [ ]:
vector = torch.tensor([7,11])
print(f"Vector:{vector}")
vector.ndim

Vector:tensor([ 7, 11])


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#matrix
matrix = torch.tensor([[1,2],[4,5]])
print(f"Matrix:{matrix}")
matrix.ndim


Matrix:tensor([[1, 2],
        [4, 5]])


2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[0]

tensor([1, 2])

In [19]:
### Random tensors
import torch
RANDOM_TENSOR = torch.rand(3,4)
RANDOM_TENSOR


tensor([[0.9335, 0.4559, 0.5693, 0.8856],
        [0.6949, 0.2850, 0.1678, 0.4761],
        [0.9793, 0.4228, 0.0510, 0.8443]])

In [29]:
RANDOM_IMAGE_SIZE_TENSOR = torch.rand(size=(3,4))
ZEROS_TENSOR = torch.zeros(size=(3,4))
ONES_TENSOR = torch.ones(size=(3,4))
RANDOM_IMAGE_SIZE_TENSOR.shape,ZEROS_TENSOR.dtype, ONES_TENSOR.dtype



(torch.Size([3, 4]), torch.float32, torch.float32)

Create a range of tensors

In [39]:
one_to_ten = torch.arange(start=1,end=11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
ten_zeros = torch.zeros_like(input=RANDOM_IMAGE_SIZE_TENSOR)
ten_zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [84]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float32)
float_64_tensor = torch.tensor([1.0,2.0,3.0],dtype=torch.float64)
float_16_tensor = float_32_tensor.type(torch.float16)
int_32_tensor = torch.tensor([3,6,9],device="cpu",dtype=torch.long)#Can use device = "cuda" to make it GPU then the multiplication won't work
print(f'Tensor Size is :{int_32_tensor.size()}')
print(f'Tensor Shape is :{int_32_tensor.shape}')
print(f'Tensor Dimension is :{int_32_tensor.ndim}')
print(f"Tensor Device is :{int_32_tensor.device}")

Tensor Size is :torch.Size([3])
Tensor Shape is :torch.Size([3])
Tensor Dimension is :1
Tensor Device is :cpu
